services:
  jenkins:
    image: jenkins-docker-in-docker:lts-jdk17
    container_name: jenkins_service
    restart: on-failure
    networks:
      jenkins:
        aliases:
          - jenkins-blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  gitea:
    image: gitea/gitea:latest
    container_name: gitea_service
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
      - GITEA__webhook__ALLOWED_HOST_LIST=172.23.164.166
    restart: always
    networks:
      jenkins:
        aliases:
          - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "8022:22"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      jenkins:
        aliases:
          - postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      jenkins:
        aliases:
          - nginx
    depends_on:
      - gitea
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
  gitea:
   driver: local